[workspace]
resolver = "2"
members = [
  "crates/http_server",
]

[workspace.dependencies]
wasm-bindgen = "0.2.87"
andy_webgl_utils = { path = "crates/andy_webgl_utils" }
wasm-bindgen-futures = "0.4.37"
js-sys = "0.3.66"
console_error_panic_hook = "0.1.7"
cgmath = "0.18.0"
web-sys = "0.3.66"



