[workspace]
resolver = "2"
members = [
  "crates/server_backend",
  "crates/pdf_parser",
  "crates/llama_runner",
  "crates/sentence_embedder",
]

[workspace.dependencies]
pdf_parser = { path = "crates/pdf_parser" }
sentence_embedder = { path = "crates/sentence_embedder" }
