name: Frontend

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install
      working-directory: ./frontend
      run: yarn install
    - name: Lint
      working-directory: ./frontend
      run: yarn eslint src
    # - name: Format
    #   working-directory: ./frontend
    #   run: yarn prettier --check ./
    - name: Build
      working-directory: ./frontend
      run: yarn run build
